### ISSUE TITLE
Missing Type Definitions for http and node-fetch in Version 2.0.1

### ISSUE THREAD

**Issue by orbanszlrd** [faisalman/ua-parser-js#776]
**Library version**
v.2.0.1

**Describe the bug**
Hello,

I'm encountering an issue with the latest version of ua-parser-js (v2.0.1) in my Angular application. 
After upgrading from v2.0.0 to v2.0.1, my build fails with the following errors:

```bash
✘ [ERROR] TS2307: Cannot find module 'http' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/ua-parser-js/src/main/ua-parser.d.ts:5:41:
      5 │ import type { IncomingHttpHeaders } from 'http';
        ╵                                          ~~~~~~
        
✘ [ERROR] TS2307: Cannot find module 'node-fetch' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/ua-parser-js/src/main/ua-parser.d.ts:6:48:
      6 │ import type { Headers as FetchAPIHeaders } from 'node-fetch';
       ╵                                                 ~~~~~~~~~~~~
```

**To Reproduce**
1. Initialize a new Angular application
3. Install ua-parser-js version 2.0.1
4. Include ua-parser-js in your project
5. Run the build process 
6. See error

**Expected behavior**
The ua-parser-js package should work without requiring additional dependencies to be manually installed by the consuming application

**Screenshots**

![Image](https://github.com/user-attachments/assets/a3ae3147-ebf1-4d1b-b2a4-b2d6aa9521a0)

**Additional context**
I managed to resolve the issue by explicitly installing the *@types/node-fetch* package in my project. 
However, I believe this should not be necessary for consumers of the *ua-parser-js* package.

**Suggested Solution:**

To ensure that consumers do not face this issue, I suggest the following action:

Move the node-fetch and @types/node-fetch packages from devDependencies to dependencies in the package.json file:

```
{
  "dependencies": {
    "node-fetch": "^2.7.0",
    "@types/node-fetch": "^2.6.12"
  }
}
```
By doing this, the ua-parser-js package can provide a seamless experience for users and avoid issues related to missing dependencies or type definitions.

Best Regards,
Szilárd

**Comment by weareukraine** [comment]
Same here

**Comment by weareukraine** [comment]
Any minor update now?

**Comment by henriquegomes6** [comment]
same problem here

**Comment by l0uisgrange** [comment]
Same here

**Comment by faisalman** [comment]
Hi, sorry for waiting, a new minor version that resolves this issue has been released now. Thanks 👍

**Comment by weareukraine** [comment]
> Hi, sorry for waiting, a new minor version that resolves this issue has been released now. Thanks 👍

Thanks a lot! Fixed. Can confirm!
