### ISSUE TITLE
WARNING in ../node_modules/ua-parser-js/src/ua-parser.js 1010:12-19 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by jvallarvisp** [faisalman/ua-parser-js#268]
Uncaught Error: Cannot find module "."

**Comment by prc333** [comment]
The same problem ，How to solve？？？？？？

**Comment by johnsiu2016** [comment]
same here

**Comment by djyde** [comment]
Same problem.

It caused by https://github.com/faisalman/ua-parser-js/commit/6f621f1ae2126f9b0c337a5e12ab0cc8258101d1#diff-600e1b113bbd6ec8ac33385938a221b3R1000

**Comment by prc333** [comment]
replace  ua-parser.js by the old file ，
can solve the problem，but why？

**Comment by zlk89** [comment]
Can use npm-shrinkwrap.json to lock the version to 0.7.15

**Comment by djyde** [comment]
@zlk89 But it was dependence by `fbjs` -> `prop-types`

**Comment by jvallarvisp** [comment]
{
  "dependencies": {
    "draft-js": {
      "version": "0.10.3",
      "from": "draft-js@0.10.3",
      "dependencies": {
        "fbjs": {
          "version": "0.8.16",
          "from": "fbjs@0.8.16",
          "dependencies": {
            "ua-parser-js": {
              "version": "0.7.9",
              "from": "ua-parser-js@~0.7.16"
            }
          }
        }
      }
    }
  }
}

**Comment by zlk89** [comment]
@djyde  npm-shrinkwrap.json lock sub-dependencies.

**Comment by Code-Master-Mr-C** [comment]
Use the previous version

**Comment by jtyjty99999** [comment]
+1

**Comment by arturhtml** [comment]
same here `Uncaught Error: Cannot find module "."`

**Comment by chenesan** [comment]
+1 `Uncaught Error: Cannot find module "."`
Rolling back to `0.7.9` works for me.

**Comment by yangbin1994** [comment]
same error!

**Comment by faisalman** [comment]
Aww sorry guys for breaking :( thanks @djyde for pointing out the error source

**Comment by fix777** [comment]
nice work! 👍👍👍

**Comment by drewjenkins** [comment]
I'm still getting this error and need to stay on 0.7.16 for the Regex DoS fix - https://snyk.io/vuln/npm:ua-parser-js:20171012?utm_source=slack

was a fix for this ever released?
